---
system_log:
  path: target/logs/error.log
  format: '%date %-5level [%thread] %logger{36} %m%n'
  level: error

http:

  connectors:
    http: 8080
    https:
      port: 8443
      tls:
        cert: core/src/test/resources/example.com.crt.pem
        key: core/src/test/resources/example.com.key.pem


  access_log:
    format: '%h %l %u [%t] "%r" %s %b "%i{Referer}" "%i{User-Agent}"'

  clusters:
    foo:
      servers:
        - 192.168.1.100: { weight: 5 }
        - 192.168.1.101: { weight: 5 }
        - 192.168.1.200
        - 192.168.1.201
    bar:
      servers:
        - 23.149.288.74
        - 23.149.288.75

  vhosts:

    vhost.com:
      aliases: ['www.vhost.com', '*.vhost.com']

      tls:
        cert: core/src/test/resources/vhost.com.pem.crt
        key: core/src/test/resources/vhost.com.pem.key

      access log: target/logs/vhosts/vhost.com/access.log

      clusters:
        foo:
          servers:
            - {weight: 5}
            - {weight: 6, size: 42, list: [5, 3, 6]}
            - 192.168.1.100: {weight: 5}
            - 192.168.1.101: {weight: 5}
            - 192.168.1.102
            - 192.168.1.103

      routes:
        /:
          - stormpath_authc
          - proxy pass: http://foo:8080